### ISSUE TITLE
Equivalent of `getState()` from redux.js

### ISSUE THREAD

**Issue by nlfiedler** [brunocodutra/reducer#34]
Using this crate I find that there is a need to get a reference to the current state, which seems impossible with the current API. For the time being, I'm registering a reactor that copies the state so a caller can get it later. Better would be a `get_state(callback: Subscription<State>)` function on the `Store` so I don't have to copy the state. At least that's what I think, you may have entirely different thoughts on this topic.

It would also be splendid if I could register more than one reactor. For now I'm maintaining my own collection of listeners.

I'd be happy to submit a pull request, although there is a chance you'd end up rewriting whatever I did.

**Comment by nlfiedler** [comment]
Sorry, just realized I used `Subscription` without any context. I got that from redux-rs, it's the function signature that takes a reference to the `State`.

**Comment by brunocodutra** [comment]
The reason why `Store` doesn't provide direct access to the inner state at the moment, is because I felt it would encourage anti-patterns that deviate from a truly reactive design, but I'd love to be given a counter example, would you mind sharing more details about your use-case?

> Better would be a `get_state(callback: Subscription<State>)` function on the `Store` so I don't have to copy the state.

Wouldn't it be sufficient for `Store<State, Reactor>` to expose a `get_state(&self) -> &State` method? Better yet, we could consider implementing `Deref<Target = State> for Store<State, Reactor>` so  that `&Store` may seamlessly be used where `&State` is expected.

> It would also be splendid if I could register more than one reactor. For now I'm maintaining my own collection of listeners.

This should be possible out-of-the-box, [tuples, arrays and slices of reactors are themselves  reactors](https://docs.rs/reducer/1.1.1/reducer/trait.Reactor.html#foreign-impls). 

The [same is true for `Reducer`s](https://docs.rs/reducer/1.1.1/reducer/trait.Reducer.html#foreign-impls) by the way.

**Comment by nlfiedler** [comment]
Certainly, a simplified `get_state()` would be fine.

Thanks for the tip on the reactors and reducers, I'll look into using that strategy.

**Comment by brunocodutra** [comment]
Sorry for the late response, I've somehow missed your update.

> now I remember why I wanted the callback to get the state: I'm using lazy_static and a Mutex to hold the application state. I don't think I can return a reference to the state to the caller when there's a mutex involved, but then again my Rust skills are not great.

This shouldn't be of any concern, it is always be possible to write a method that gets a `&'a S` out of `&'a Store<S, R>`, regardless of what `S` is. 

For example, If `S` is `MyState(Mutex<SomeData>)`, you'll get a `&MyState` back. You're then free to lock the mutex to get access to `SomeData` if you like.

Does that make sense?

**Comment by nlfiedler** [comment]
Ah, right, thanks for pointing that out. It adds a step for the caller, but it's an alternative to copying, which is what I'm doing now.

**Comment by nlfiedler** [comment]
I've put this fix to good use (copying the state when I need it rather than on every update). Thanks for taking the time to explain, and for addressing this request.
